#!/bin/sh
set -e
######## detekt-GRADLE HOOK START ########

CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.kt/ { print $2}' | paste -sd "," -)"

if [ -z "$CHANGED_FILES" ]; then
    echo "No Kotlin staged files."
    exit 0
fi;

echo "Running detekt over these files:"
echo "$CHANGED_FILES"

./gradlew detekt -PinputProps="$CHANGED_FILES"

echo "Completed detekt run."

echo "$CHANGED_FILES" | while read -r file; do
    if [ -f $file ]; then
        git add $file
    fi
done

echo "Completed ktlint hook."
######## detekt-GRADLE HOOK END ########
